!/bin/sh

python regress_binned_FI_LSTM.py --name sc_ctZ_TTG   --config ttG_WG --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTGWG --config ttG_WG --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTG   --config ttG_WG --add_LSTM --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTGWG --config ttG_WG --add_LSTM --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTG   --config ttG_WG --weighted_training --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTGWG --config ttG_WG --weighted_training --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTG   --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTGWG --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTG   --config ttG_WG --add_weighted_quantiles  --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTGWG --config ttG_WG --add_weighted_quantiles  --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTG   --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTGWG --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctZ_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_ctZ_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root

python regress_binned_FI_LSTM.py --name sc_cpQ3_TTG   --config ttG_WG --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTGWG --config ttG_WG --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTG   --config ttG_WG --add_LSTM --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTGWG --config ttG_WG --add_LSTM --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTG   --config ttG_WG --weighted_training --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTGWG --config ttG_WG --weighted_training --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTG   --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTGWG --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTG   --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTGWG --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTG   --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTGWG --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpQ3_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cpQ3_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root

python regress_binned_FI_LSTM.py --name sc_cpG_TTG   --config ttG_WG --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTGWG --config ttG_WG --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTG   --config ttG_WG --add_LSTM --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTGWG --config ttG_WG --add_LSTM --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTG   --config ttG_WG --weighted_training --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTGWG --config ttG_WG --weighted_training --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTG   --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTGWG --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTG   --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTGWG --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTG   --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTGWG --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpG_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cpG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root

python regress_binned_FI_LSTM.py --name sc_ctG_TTG   --config ttG_WG --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTGWG --config ttG_WG --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTG   --config ttG_WG --add_LSTM --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTGWG --config ttG_WG --add_LSTM --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTG   --config ttG_WG --weighted_training --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTGWG --config ttG_WG --weighted_training --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTG   --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTGWG --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTG   --config ttG_WG --add_weighted_quantiles  --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTGWG --config ttG_WG --add_weighted_quantiles  --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTG   --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTGWG --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_ctG_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_ctG_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root

python regress_binned_FI_LSTM.py --name sc_cpWB_TTG   --config ttG_WG --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTGWG --config ttG_WG --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTG   --config ttG_WG --add_LSTM --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTGWG --config ttG_WG --add_LSTM --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTG   --config ttG_WG --weighted_training --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTGWG --config ttG_WG --weighted_training --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTG   --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTGWG --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTG   --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTGWG --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTG   --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTGWG --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpWB_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cpWB_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root

python regress_binned_FI_LSTM.py --name sc_cpDC_TTG   --config ttG_WG --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTGWG --config ttG_WG --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTG   --config ttG_WG --add_LSTM --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTGWG --config ttG_WG --add_LSTM --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTG   --config ttG_WG --weighted_training --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTGWG --config ttG_WG --weighted_training --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTG   --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTGWG --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTG   --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTGWG --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTG   --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTGWG --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cpDC_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cpDC_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root

python regress_binned_FI_LSTM.py --name sc_cWWW_TTG   --config ttG_WG --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTGWG --config ttG_WG --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTG   --config ttG_WG --add_LSTM --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTGWG --config ttG_WG --add_LSTM --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTG   --config ttG_WG --weighted_training --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTGWG --config ttG_WG --weighted_training --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTG   --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTGWG --config ttG_WG --weighted_training --add_LSTM --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTG   --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTGWG --config ttG_WG --add_weighted_quantiles  --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTG   --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTGWG --config ttG_WG --add_weighted_quantiles --add_LSTM --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTG   --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root
python regress_binned_FI_LSTM.py --name sc_cWWW_TTGWG --config ttG_WG --add_weighted_quantiles --weighted_training --add_LSTM --FI_branch FI_cWWW_BSM --trainingfile ttG_noFullyHad_fast/singlelep-photon/ttG_noFullyHad_fast.root WGToLNu_fast/singlelep-photon/WGToLNu_fast.root
