python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 20 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 40 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 80 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 100 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 200 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 400 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 10 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 5 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 1 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 2 --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_photon_pt --bin_number 10000 --rel_max_local_score_test 0.001 
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_ht --bin_number 40 --min_bin 0. --max_bin 1600. --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_ht --bin_number 20 --min_bin 0. --max_bin 1600. --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_l1_pt --bin_number 20 --min_bin 0. --max_bin 400. --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_l1_pt --bin_number 40 --min_bin 0. --max_bin 400. --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_nJetGood --bin_number 8 --min_bin 0. --max_bin 8. --rel_max_local_score_test 0.001
python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.001 --name_dir LLR_0.001 --binning_var mva_nBTag --bin_number 5 --min_bin 0. --max_bin 5. --rel_max_local_score_test 0.001

#python plots_ttg.py --debug --input_directory /scratch-cbe/users/robert.schoefbeck/BIT/training-ntuples-ttG_WG/MVA-training/ttG_WG --config ttG_WG  --name capScore_training_0.01 --name_dir LLR_test_0.01_full
