python run_cf.py --overwrite --lumi 1
#python run_cf.py --overwrite --lumi 1.1
#python run_cf.py --overwrite --lumi 1.2
#python run_cf.py --overwrite --lumi 1.3
#python run_cf.py --overwrite --lumi 1.4
#python run_cf.py --overwrite --lumi 1.5
#python run_cf.py --overwrite --lumi 1.6
#python run_cf.py --overwrite --lumi 1.7
#python run_cf.py --overwrite --lumi 1.8
#python run_cf.py --overwrite --lumi 1.9
python run_cf.py --overwrite --lumi 2
#python run_cf.py --overwrite --lumi 2.1
#python run_cf.py --overwrite --lumi 2.2
#python run_cf.py --overwrite --lumi 2.3
#python run_cf.py --overwrite --lumi 2.4
#python run_cf.py --overwrite --lumi 2.5
#python run_cf.py --overwrite --lumi 2.6
#python run_cf.py --overwrite --lumi 2.7
#python run_cf.py --overwrite --lumi 2.8
#python run_cf.py --overwrite --lumi 2.9
python run_cf.py --overwrite --lumi 3
#python run_cf.py --overwrite --lumi 3.1
#python run_cf.py --overwrite --lumi 3.2
#python run_cf.py --overwrite --lumi 3.3
#python run_cf.py --overwrite --lumi 3.4
#python run_cf.py --overwrite --lumi 3.5
#python run_cf.py --overwrite --lumi 3.6
#python run_cf.py --overwrite --lumi 3.7
#python run_cf.py --overwrite --lumi 3.8
#python run_cf.py --overwrite --lumi 3.9
python run_cf.py --overwrite --lumi 4
#python run_cf.py --overwrite --lumi 4.1
#python run_cf.py --overwrite --lumi 4.2
#python run_cf.py --overwrite --lumi 4.3
#python run_cf.py --overwrite --lumi 4.4
#python run_cf.py --overwrite --lumi 4.5
#python run_cf.py --overwrite --lumi 4.6
#python run_cf.py --overwrite --lumi 4.7
#python run_cf.py --overwrite --lumi 4.8
#python run_cf.py --overwrite --lumi 4.9
python run_cf.py --overwrite --lumi 5
#python run_cf.py --overwrite --lumi 5.1
#python run_cf.py --overwrite --lumi 5.2
#python run_cf.py --overwrite --lumi 5.3
#python run_cf.py --overwrite --lumi 5.4
#python run_cf.py --overwrite --lumi 5.5
#python run_cf.py --overwrite --lumi 5.6
#python run_cf.py --overwrite --lumi 5.7
#python run_cf.py --overwrite --lumi 5.8
#python run_cf.py --overwrite --lumi 5.9
python run_cf.py --overwrite --lumi 6
#python run_cf.py --overwrite --lumi 6.1
#python run_cf.py --overwrite --lumi 6.2
#python run_cf.py --overwrite --lumi 6.3
#python run_cf.py --overwrite --lumi 6.4
#python run_cf.py --overwrite --lumi 6.5
#python run_cf.py --overwrite --lumi 6.6
#python run_cf.py --overwrite --lumi 6.7
#python run_cf.py --overwrite --lumi 6.8
#python run_cf.py --overwrite --lumi 6.9
python run_cf.py --overwrite --lumi 7
#python run_cf.py --overwrite --lumi 7.1
#python run_cf.py --overwrite --lumi 7.2
#python run_cf.py --overwrite --lumi 7.3
#python run_cf.py --overwrite --lumi 7.4
#python run_cf.py --overwrite --lumi 7.5
#python run_cf.py --overwrite --lumi 7.6
#python run_cf.py --overwrite --lumi 7.7
#python run_cf.py --overwrite --lumi 7.8
#python run_cf.py --overwrite --lumi 7.9
python run_cf.py --overwrite --lumi 8
#python run_cf.py --overwrite --lumi 8.1
#python run_cf.py --overwrite --lumi 8.2
#python run_cf.py --overwrite --lumi 8.3
#python run_cf.py --overwrite --lumi 8.4
#python run_cf.py --overwrite --lumi 8.5
#python run_cf.py --overwrite --lumi 8.6
#python run_cf.py --overwrite --lumi 8.7
#python run_cf.py --overwrite --lumi 8.8
#python run_cf.py --overwrite --lumi 8.9
python run_cf.py --overwrite --lumi 9
#python run_cf.py --overwrite --lumi 9.1
#python run_cf.py --overwrite --lumi 9.2
#python run_cf.py --overwrite --lumi 9.3
#python run_cf.py --overwrite --lumi 9.4
#python run_cf.py --overwrite --lumi 9.5
#python run_cf.py --overwrite --lumi 9.6
#python run_cf.py --overwrite --lumi 9.7
#python run_cf.py --overwrite --lumi 9.8
#python run_cf.py --overwrite --lumi 9.9
python run_cf.py --overwrite --lumi 10
#python run_cf.py --overwrite --lumi 10.1
#python run_cf.py --overwrite --lumi 10.2
#python run_cf.py --overwrite --lumi 10.3
#python run_cf.py --overwrite --lumi 10.4
#python run_cf.py --overwrite --lumi 10.5
#python run_cf.py --overwrite --lumi 10.6
#python run_cf.py --overwrite --lumi 10.7
#python run_cf.py --overwrite --lumi 10.8
#python run_cf.py --overwrite --lumi 10.9
python run_cf.py --overwrite --lumi 11
#python run_cf.py --overwrite --lumi 11.1
#python run_cf.py --overwrite --lumi 11.2
#python run_cf.py --overwrite --lumi 11.3
#python run_cf.py --overwrite --lumi 11.4
#python run_cf.py --overwrite --lumi 11.5
#python run_cf.py --overwrite --lumi 11.6
#python run_cf.py --overwrite --lumi 11.7
#python run_cf.py --overwrite --lumi 11.8
#python run_cf.py --overwrite --lumi 11.9
python run_cf.py --overwrite --lumi 12
#python run_cf.py --overwrite --lumi 12.1
#python run_cf.py --overwrite --lumi 12.2
#python run_cf.py --overwrite --lumi 12.3
#python run_cf.py --overwrite --lumi 12.4
#python run_cf.py --overwrite --lumi 12.5
#python run_cf.py --overwrite --lumi 12.6
#python run_cf.py --overwrite --lumi 12.7
#python run_cf.py --overwrite --lumi 12.8
#python run_cf.py --overwrite --lumi 12.9
python run_cf.py --overwrite --lumi 13
#python run_cf.py --overwrite --lumi 13.1
#python run_cf.py --overwrite --lumi 13.2
#python run_cf.py --overwrite --lumi 13.3
#python run_cf.py --overwrite --lumi 13.4
#python run_cf.py --overwrite --lumi 13.5
#python run_cf.py --overwrite --lumi 13.6
#python run_cf.py --overwrite --lumi 13.7
#python run_cf.py --overwrite --lumi 13.8
#python run_cf.py --overwrite --lumi 13.9
python run_cf.py --overwrite --lumi 14
#python run_cf.py --overwrite --lumi 14.1
#python run_cf.py --overwrite --lumi 14.2
#python run_cf.py --overwrite --lumi 14.3
#python run_cf.py --overwrite --lumi 14.4
#python run_cf.py --overwrite --lumi 14.5
#python run_cf.py --overwrite --lumi 14.6
#python run_cf.py --overwrite --lumi 14.7
#python run_cf.py --overwrite --lumi 14.8
#python run_cf.py --overwrite --lumi 14.9
python run_cf.py --overwrite --lumi 15
#python run_cf.py --overwrite --lumi 15.1
#python run_cf.py --overwrite --lumi 15.2
#python run_cf.py --overwrite --lumi 15.3
#python run_cf.py --overwrite --lumi 15.4
#python run_cf.py --overwrite --lumi 15.5
#python run_cf.py --overwrite --lumi 15.6
#python run_cf.py --overwrite --lumi 15.7
#python run_cf.py --overwrite --lumi 15.8
#python run_cf.py --overwrite --lumi 15.9
python run_cf.py --overwrite --lumi 16
#python run_cf.py --overwrite --lumi 16.1
#python run_cf.py --overwrite --lumi 16.2
#python run_cf.py --overwrite --lumi 16.3
#python run_cf.py --overwrite --lumi 16.4
#python run_cf.py --overwrite --lumi 16.5
#python run_cf.py --overwrite --lumi 16.6
#python run_cf.py --overwrite --lumi 16.7
#python run_cf.py --overwrite --lumi 16.8
#python run_cf.py --overwrite --lumi 16.9
python run_cf.py --overwrite --lumi 17
#python run_cf.py --overwrite --lumi 17.1
#python run_cf.py --overwrite --lumi 17.2
#python run_cf.py --overwrite --lumi 17.3
#python run_cf.py --overwrite --lumi 17.4
#python run_cf.py --overwrite --lumi 17.5
#python run_cf.py --overwrite --lumi 17.6
#python run_cf.py --overwrite --lumi 17.7
#python run_cf.py --overwrite --lumi 17.8
#python run_cf.py --overwrite --lumi 17.9
python run_cf.py --overwrite --lumi 18
#python run_cf.py --overwrite --lumi 18.1
#python run_cf.py --overwrite --lumi 18.2
#python run_cf.py --overwrite --lumi 18.3
#python run_cf.py --overwrite --lumi 18.4
#python run_cf.py --overwrite --lumi 18.5
#python run_cf.py --overwrite --lumi 18.6
#python run_cf.py --overwrite --lumi 18.7
#python run_cf.py --overwrite --lumi 18.8
#python run_cf.py --overwrite --lumi 18.9
python run_cf.py --overwrite --lumi 19
#python run_cf.py --overwrite --lumi 19.1
#python run_cf.py --overwrite --lumi 19.2
#python run_cf.py --overwrite --lumi 19.3
#python run_cf.py --overwrite --lumi 19.4
#python run_cf.py --overwrite --lumi 19.5
#python run_cf.py --overwrite --lumi 19.6
#python run_cf.py --overwrite --lumi 19.7
#python run_cf.py --overwrite --lumi 19.8
#python run_cf.py --overwrite --lumi 19.9
python run_cf.py --overwrite --lumi 20
#python run_cf.py --overwrite --lumi 20.1
#python run_cf.py --overwrite --lumi 20.2
#python run_cf.py --overwrite --lumi 20.3
#python run_cf.py --overwrite --lumi 20.4
#python run_cf.py --overwrite --lumi 20.5
#python run_cf.py --overwrite --lumi 20.6
#python run_cf.py --overwrite --lumi 20.7
#python run_cf.py --overwrite --lumi 20.8
#python run_cf.py --overwrite --lumi 20.9
python run_cf.py --overwrite --lumi 21
#python run_cf.py --overwrite --lumi 21.1
#python run_cf.py --overwrite --lumi 21.2
#python run_cf.py --overwrite --lumi 21.3
#python run_cf.py --overwrite --lumi 21.4
#python run_cf.py --overwrite --lumi 21.5
#python run_cf.py --overwrite --lumi 21.6
#python run_cf.py --overwrite --lumi 21.7
#python run_cf.py --overwrite --lumi 21.8
#python run_cf.py --overwrite --lumi 21.9
python run_cf.py --overwrite --lumi 22
#python run_cf.py --overwrite --lumi 22.1
#python run_cf.py --overwrite --lumi 22.2
#python run_cf.py --overwrite --lumi 22.3
#python run_cf.py --overwrite --lumi 22.4
#python run_cf.py --overwrite --lumi 22.5
#python run_cf.py --overwrite --lumi 22.6
#python run_cf.py --overwrite --lumi 22.7
#python run_cf.py --overwrite --lumi 22.8
#python run_cf.py --overwrite --lumi 22.9
python run_cf.py --overwrite --lumi 23
#python run_cf.py --overwrite --lumi 23.1
#python run_cf.py --overwrite --lumi 23.2
#python run_cf.py --overwrite --lumi 23.3
#python run_cf.py --overwrite --lumi 23.4
#python run_cf.py --overwrite --lumi 23.5
#python run_cf.py --overwrite --lumi 23.6
#python run_cf.py --overwrite --lumi 23.7
#python run_cf.py --overwrite --lumi 23.8
#python run_cf.py --overwrite --lumi 23.9
python run_cf.py --overwrite --lumi 24
#python run_cf.py --overwrite --lumi 24.1
#python run_cf.py --overwrite --lumi 24.2
#python run_cf.py --overwrite --lumi 24.3
#python run_cf.py --overwrite --lumi 24.4
#python run_cf.py --overwrite --lumi 24.5
#python run_cf.py --overwrite --lumi 24.6
#python run_cf.py --overwrite --lumi 24.7
#python run_cf.py --overwrite --lumi 24.8
#python run_cf.py --overwrite --lumi 24.9
python run_cf.py --overwrite --lumi 25
#python run_cf.py --overwrite --lumi 25.1
#python run_cf.py --overwrite --lumi 25.2
#python run_cf.py --overwrite --lumi 25.3
#python run_cf.py --overwrite --lumi 25.4
#python run_cf.py --overwrite --lumi 25.5
#python run_cf.py --overwrite --lumi 25.6
#python run_cf.py --overwrite --lumi 25.7
#python run_cf.py --overwrite --lumi 25.8
#python run_cf.py --overwrite --lumi 25.9
python run_cf.py --overwrite --lumi 26
#python run_cf.py --overwrite --lumi 26.1
#python run_cf.py --overwrite --lumi 26.2
#python run_cf.py --overwrite --lumi 26.3
#python run_cf.py --overwrite --lumi 26.4
#python run_cf.py --overwrite --lumi 26.5
#python run_cf.py --overwrite --lumi 26.6
#python run_cf.py --overwrite --lumi 26.7
#python run_cf.py --overwrite --lumi 26.8
#python run_cf.py --overwrite --lumi 26.9
python run_cf.py --overwrite --lumi 27
#python run_cf.py --overwrite --lumi 27.1
#python run_cf.py --overwrite --lumi 27.2
#python run_cf.py --overwrite --lumi 27.3
#python run_cf.py --overwrite --lumi 27.4
#python run_cf.py --overwrite --lumi 27.5
#python run_cf.py --overwrite --lumi 27.6
#python run_cf.py --overwrite --lumi 27.7
#python run_cf.py --overwrite --lumi 27.8
#python run_cf.py --overwrite --lumi 27.9
python run_cf.py --overwrite --lumi 28
#python run_cf.py --overwrite --lumi 28.1
#python run_cf.py --overwrite --lumi 28.2
#python run_cf.py --overwrite --lumi 28.3
#python run_cf.py --overwrite --lumi 28.4
#python run_cf.py --overwrite --lumi 28.5
#python run_cf.py --overwrite --lumi 28.6
#python run_cf.py --overwrite --lumi 28.7
#python run_cf.py --overwrite --lumi 28.8
#python run_cf.py --overwrite --lumi 28.9
python run_cf.py --overwrite --lumi 29
#python run_cf.py --overwrite --lumi 29.1
#python run_cf.py --overwrite --lumi 29.2
#python run_cf.py --overwrite --lumi 29.3
#python run_cf.py --overwrite --lumi 29.4
#python run_cf.py --overwrite --lumi 29.5
#python run_cf.py --overwrite --lumi 29.6
#python run_cf.py --overwrite --lumi 29.7
#python run_cf.py --overwrite --lumi 29.8
#python run_cf.py --overwrite --lumi 29.9
python run_cf.py --overwrite --lumi 30
#python run_cf.py --overwrite --lumi 30.1
#python run_cf.py --overwrite --lumi 30.2
#python run_cf.py --overwrite --lumi 30.3
#python run_cf.py --overwrite --lumi 30.4
#python run_cf.py --overwrite --lumi 30.5
#python run_cf.py --overwrite --lumi 30.6
#python run_cf.py --overwrite --lumi 30.7
#python run_cf.py --overwrite --lumi 30.8
#python run_cf.py --overwrite --lumi 30.9
python run_cf.py --overwrite --lumi 31
#python run_cf.py --overwrite --lumi 31.1
#python run_cf.py --overwrite --lumi 31.2
#python run_cf.py --overwrite --lumi 31.3
#python run_cf.py --overwrite --lumi 31.4
#python run_cf.py --overwrite --lumi 31.5
#python run_cf.py --overwrite --lumi 31.6
#python run_cf.py --overwrite --lumi 31.7
#python run_cf.py --overwrite --lumi 31.8
#python run_cf.py --overwrite --lumi 31.9
python run_cf.py --overwrite --lumi 32
#python run_cf.py --overwrite --lumi 32.1
#python run_cf.py --overwrite --lumi 32.2
#python run_cf.py --overwrite --lumi 32.3
#python run_cf.py --overwrite --lumi 32.4
#python run_cf.py --overwrite --lumi 32.5
#python run_cf.py --overwrite --lumi 32.6
#python run_cf.py --overwrite --lumi 32.7
#python run_cf.py --overwrite --lumi 32.8
#python run_cf.py --overwrite --lumi 32.9
python run_cf.py --overwrite --lumi 33
#python run_cf.py --overwrite --lumi 33.1
#python run_cf.py --overwrite --lumi 33.2
#python run_cf.py --overwrite --lumi 33.3
#python run_cf.py --overwrite --lumi 33.4
#python run_cf.py --overwrite --lumi 33.5
#python run_cf.py --overwrite --lumi 33.6
#python run_cf.py --overwrite --lumi 33.7
#python run_cf.py --overwrite --lumi 33.8
#python run_cf.py --overwrite --lumi 33.9
python run_cf.py --overwrite --lumi 34
#python run_cf.py --overwrite --lumi 34.1
#python run_cf.py --overwrite --lumi 34.2
#python run_cf.py --overwrite --lumi 34.3
#python run_cf.py --overwrite --lumi 34.4
#python run_cf.py --overwrite --lumi 34.5
#python run_cf.py --overwrite --lumi 34.6
#python run_cf.py --overwrite --lumi 34.7
#python run_cf.py --overwrite --lumi 34.8
#python run_cf.py --overwrite --lumi 34.9
python run_cf.py --overwrite --lumi 35
#python run_cf.py --overwrite --lumi 35.1
#python run_cf.py --overwrite --lumi 35.2
#python run_cf.py --overwrite --lumi 35.3
#python run_cf.py --overwrite --lumi 35.4
#python run_cf.py --overwrite --lumi 35.5
#python run_cf.py --overwrite --lumi 35.6
#python run_cf.py --overwrite --lumi 35.7
#python run_cf.py --overwrite --lumi 35.8
#python run_cf.py --overwrite --lumi 35.9
python run_cf.py --overwrite --lumi 36
#python run_cf.py --overwrite --lumi 36.1
#python run_cf.py --overwrite --lumi 36.2
#python run_cf.py --overwrite --lumi 36.3
#python run_cf.py --overwrite --lumi 36.4
#python run_cf.py --overwrite --lumi 36.5
#python run_cf.py --overwrite --lumi 36.6
#python run_cf.py --overwrite --lumi 36.7
#python run_cf.py --overwrite --lumi 36.8
#python run_cf.py --overwrite --lumi 36.9
python run_cf.py --overwrite --lumi 37
#python run_cf.py --overwrite --lumi 37.1
#python run_cf.py --overwrite --lumi 37.2
#python run_cf.py --overwrite --lumi 37.3
#python run_cf.py --overwrite --lumi 37.4
#python run_cf.py --overwrite --lumi 37.5
#python run_cf.py --overwrite --lumi 37.6
#python run_cf.py --overwrite --lumi 37.7
#python run_cf.py --overwrite --lumi 37.8
#python run_cf.py --overwrite --lumi 37.9
python run_cf.py --overwrite --lumi 38
#python run_cf.py --overwrite --lumi 38.1
#python run_cf.py --overwrite --lumi 38.2
#python run_cf.py --overwrite --lumi 38.3
#python run_cf.py --overwrite --lumi 38.4
#python run_cf.py --overwrite --lumi 38.5
#python run_cf.py --overwrite --lumi 38.6
#python run_cf.py --overwrite --lumi 38.7
#python run_cf.py --overwrite --lumi 38.8
#python run_cf.py --overwrite --lumi 38.9
python run_cf.py --overwrite --lumi 39
#python run_cf.py --overwrite --lumi 39.1
#python run_cf.py --overwrite --lumi 39.2
#python run_cf.py --overwrite --lumi 39.3
#python run_cf.py --overwrite --lumi 39.4
#python run_cf.py --overwrite --lumi 39.5
#python run_cf.py --overwrite --lumi 39.6
#python run_cf.py --overwrite --lumi 39.7
#python run_cf.py --overwrite --lumi 39.8
#python run_cf.py --overwrite --lumi 39.9
python run_cf.py --overwrite --lumi 40
#python run_cf.py --overwrite --lumi 40.1
#python run_cf.py --overwrite --lumi 40.2
#python run_cf.py --overwrite --lumi 40.3
#python run_cf.py --overwrite --lumi 40.4
#python run_cf.py --overwrite --lumi 40.5
#python run_cf.py --overwrite --lumi 40.6
#python run_cf.py --overwrite --lumi 40.7
#python run_cf.py --overwrite --lumi 40.8
#python run_cf.py --overwrite --lumi 40.9
