#!/bin/sh

python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTG_LSTM/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTG/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTGWG_LSTM/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTGWG/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTGWG_wq_LSTM/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTGWG_wq/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTGWG_wtr_LSTM/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTGWG_wtr/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTGWG_wtr_wq_LSTM/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTGWG_wtr_wq/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTG_wq_LSTM/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTG_wq/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTG_wtr_LSTM/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTG_wtr/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTG_wtr_wq_LSTM/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpDC --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpDC_TTG_wtr_wq/ttG_WG/FI_cpDC_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTG_LSTM/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTG/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTGWG_LSTM/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTGWG/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTGWG_wq_LSTM/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTGWG_wq/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTGWG_wtr_LSTM/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTGWG_wtr/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTG_wq_LSTM/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTG_wq/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTG_wtr_LSTM/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTG_wtr/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTG_wtr_wq_LSTM/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpG_TTG_wtr_wq/ttG_WG/FI_cpG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTG_LSTM/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTG/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTGWG_wq_LSTM/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTGWG_wq/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTGWG_wtr_LSTM/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTGWG_wtr/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTGWG_wtr_wq_LSTM/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTGWG_wtr_wq/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTG_wq_LSTM/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTG_wq/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTG_wtr_LSTM/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTG_wtr/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTG_wtr_wq_LSTM/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpQ3 --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpQ3_TTG_wtr_wq/ttG_WG/FI_cpQ3_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTG_LSTM/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTG/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTGWG_LSTM/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTGWG/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTGWG_wq_LSTM/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTGWG_wq/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTGWG_wtr_LSTM/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTGWG_wtr/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTGWG_wtr_wq_LSTM/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTGWG_wtr_wq/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTG_wq_LSTM/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTG_wq/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTG_wtr_LSTM/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTG_wtr/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTG_wtr_wq_LSTM/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cpWB --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cpWB_TTG_wtr_wq/ttG_WG/FI_cpWB_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTG_LSTM/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTG/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTGWG_LSTM/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTGWG/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTGWG_wq_LSTM/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTGWG_wq/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTGWG_wtr_LSTM/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTGWG_wtr/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTGWG_wtr_wq_LSTM/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTGWG_wtr_wq/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTG_wq_LSTM/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTG_wq/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTG_wtr_LSTM/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTG_wtr/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTG_wtr_wq_LSTM/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctG --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctG_TTG_wtr_wq/ttG_WG/FI_ctG_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTG_LSTM/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTG/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTGWG_LSTM/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTGWG/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTGWG_wq_LSTM/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTGWG_wq/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTGWG_wtr_LSTM/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTGWG_wtr/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTG_wq_LSTM/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTG_wq/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTG_wtr_LSTM/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTG_wtr/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTG_wtr_wq_LSTM/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC ctZ --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_ctZ_TTG_wtr_wq/ttG_WG/FI_ctZ_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTG_LSTM/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTG/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTGWG_LSTM/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTGWG/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTGWG_wq_LSTM/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTGWG_wq/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTGWG_wtr_LSTM/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTGWG_wtr/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTG_wq_LSTM/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTG_wq/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTG_wtr_LSTM/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTG_wtr/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTG_wtr_wq_LSTM/ttG_WG/FI_cWWW_BSM/regression_model.h5
python analysis-singlelep.py --small --WC cWWW --onlyMVA /mnt/hephy/cms/robert.schoefbeck/TMB/models/sc2_cWWW_TTG_wtr_wq/ttG_WG/FI_cWWW_BSM/regression_model.h5
