python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cp
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cpBB
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cpW
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cdp
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC ctp
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cpDC
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cWWW
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cpWB
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cpQ3
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cpQM
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cpt
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC ctZ
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC ctG
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cG
python binned_FI.py  --sample ttG_noFullyHad_fast --WCval  1.0 --WC cpG

python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cp
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cpBB
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cpW
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cdp
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC ctp
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cpDC
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cWWW
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cpWB
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cpQ3
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cpQM
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cpt
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC ctG
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cG
python binned_FI.py  --sample WGToLNu_fast --WCval  1.0 --WC cpG
