python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cp
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpBB
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpW
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cdp
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC ctp
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpDC
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cWWW
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpWB
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpQ3
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpQM
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpt
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC ctZ
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC ctG
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cG
python singlelep.py --sample ttG_noFullyHad_fast  --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpG

python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cp
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpBB
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpW
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cdp
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC ctp
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpDC
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cWWW
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpWB
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpQ3
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpQM
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpt
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC ctG
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cG
python singlelep.py --sample WGToLNu_fast --WCval -1.0 1.0 --WCval_FI 0.0 1.0 --WC cpG
